# Generated by Django 6.0.3 on 2026-05-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
